### ISSUE TITLE
Sub transfer

### ISSUE THREAD

**Issue by christoskogios03** [rddim/FreeTubePortable#1]
Is there a way to transfer my subscriptions from one pc to another without going through the whole process of subscribing to every channel?

**Comment by christoskogios03** [comment]
Nevermind I just talk way too early

**Comment by rddim** [comment]
Yes, there is [Importing Your YouTube Subscriptions From other FreeTube instances ](https://github.com/FreeTubeApp/FreeTube/wiki/Importing-Your-YouTube-Subscriptions#from-other-freetube-instances)
