### ISSUE TITLE
Update FreeTubePortable to v0.22.1-beta

### ISSUE THREAD

**Issue by sunlightspectre** [rddim/FreeTubePortable#5]
Hello, 

Thanks for creating and maintaining this.  
I vastly prefer portable installers, and even though there's a 'portable' build in the indev git for freetube, it doesn't respect the settings I've built up. That could very well be user error, but the simple truth of it is that I prefer yours!   
So if you have the time, it'd mean a lot if you could update to v0.22.1-beta, as there is a fairly prominent but that makes watching most videos impossible on older versions right now.

Regardless, thank you for your time and work!..

**Comment by rddim** [comment]
@sunlightspectre 

Already done, please visit https://github.com/rddim/FreeTubePortable/releases/latest
