### ISSUE TITLE
Build names are going to change

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [rddim/FreeTubePortable#6]
Hi i would like to inform you that some of our build names are going to change and you could be affected by this, see https://github.com/FreeTubeApp/FreeTube/pull/6423

**Comment by rddim** [comment]
Thank you very much for the notification!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @rddim asset names getting a minor adjustment, see https://github.com/FreeTubeApp/FreeTube/pull/7512
